name: "Wait For Vercel"
description: "Wait for Vercel deployment to finish"
author: "GennYoon"
inputs:
  token:
    description: "Vercel Token"
    required: true
  project-id:
    description: "Vercel Project ID"
    required: true
  team-id:
    description: "Vercel Team ID"
    required: false
  timeout:
    description: "Timeout in seconds"
    required: false
    default: 600
  sha:
    description: "The commit sha to wait for"
    required: true

outputs:
  url:
    description: 'The deployment url'
    value: ${{ steps.vercel-wait.outputs.url }}

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "clock"
  color: "white"

